package dev.ranieri.entities;

// Spring Data is an ORM Object Relational Mapper
// It can take my classes in Java and Relate them to specific tables in the database
// The relationship is defined through annotations

import javax.persistence.*;

@Entity // this is a class designed to be saved in a database
@Table(name = "book") // the table in the database the class maps to
public class Book {

    @Id // for the field that is the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // The value in this field is auto-generated by the database
    @Column(name = "id")// name of the column in the database
    private int id;

    @Column(name = "title")
    private String title;

    @Column(name = "author")
    private String author;

    @Column(name = "return_date")
    private long returnDate;

    public Book() {
    }

    public Book(int id, String title, String author, long returnDate) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.returnDate = returnDate;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public long getReturnDate() {
        return returnDate;
    }

    public void setReturnDate(long returnDate) {
        this.returnDate = returnDate;
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", author='" + author + '\'' +
                ", returnDate=" + returnDate +
                '}';
    }
}
